services:
  database:
    build:
      context: ./db
      dockerfile: dockerfile
    volumes:
      - ./volumes/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "UCMStudents6"
      POSTGRES_PASSWORD: "KRKT86V9wr8tkGHkQN6tM8mHDmk2R7"
      POSTGRES_DB: "mydb"
    ports:
      - "6361:5432"

  interface:
    build:
      context: ./interface
      dockerfile: dockerfile
    depends_on:
      - database

    volumes:
      - ./volumes/pickle-data:/app/pickle-data/
      - ./volumes/llm-repos:/app/llm-datasets/
    command:
      # ["sh", "/app/setup.sh"]
    ports:
      - "6360:5000"