services:
  database:
    build:
      context: ./db
      dockerfile: dockerfile
    volumes:
      - ./volumes/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  interface:
    build:
      context: ./interface
      dockerfile: dockerfile
    volumes:
      - ./volumes/pickle-data:/app/pickle-data/
    ports:
      - "8000:5000"