services:
  interface:
    build:
      context: ./interface
      dockerfile: dockerfile
    volumes:
      - ./volumes/pickle-data:/app/pickle-data/
      - ./volumes/llm-datasets:/app/llm-datasets/
    command:
      # ["sh", "/app/setup.sh"]
    ports:
      - "6360:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]