# Created by: AJ Grant
# 2024-05-01
# docker-compose.yaml

services:
  interface:
    build:
      context: ./interface
      dockerfile: dockerfile
    volumes:
      - ./volumes/pickle-data:/app/pickle-data/
      - ./volumes/llm-datasets:/app/llm-datasets/
      - ./volumes/checkpoint-files:/app/results/
      - ./volumes/cache:/root/.cache/
    command:
      # ["sh", "/app/setup.sh"]
      # ["nvidia-smi"]
    ports:
      - "6360:5000"

    #! If your device does not have a Nvidia GPU,
    #! comment out the code below!
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "0"
              capabilities: [gpu]