services:
  database:
    build:
      context: ./db
      dockerfile: dockerfile
    volumes:
      - ./volumes/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  interface:
    build:
      context: ./interface
      dockerfile: dockerfile
    depends_on:
      - database
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY} #! Replace with your OpenAI API key. DO NOT COMMIT THIS FILE WITH YOUR API KEY
    volumes:
      - ./volumes/pickle-data:/app/pickle-data/
    ports:
      - "8000:5000"