services:
  database:
    build:
      context: ./db
      dockerfile: dockerfile
    volumes:
      - ./volumes/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "6361:5432"

  interface:
    build:
      context: ./interface
      dockerfile: dockerfile
    depends_on:
      - database

    volumes:
      - ./volumes/pickle-data:/app/pickle-data/
      - ./volumes/llm-repos:/app/llm-datasets/
    command:
      # ["sh", "/app/setup.sh"]
    ports:
      - "6360:5000"