# Use the official PostgreSQL image as the base image
FROM postgres:latest

# !TODO: Collect username and passwords from somewhere else
# Set environment variables for PostgreSQL
ENV POSTGRES_DB=mydb
ENV POSTGRES_USER=UCMStudents6
ENV POSTGRES_PASSWORD=KRKT86V9wr8tkGHkQN6tM8mHDmk2R7

# Expose the PostgreSQL port
EXPOSE 5432
