# AJ Grant
# 2024-05-01
# Dockerfile for the chat-cats application


# Use the base image as the parent image
FROM ajgrant6/chat-cats-base:latest

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=run.py

# Run app.py when the container launches
CMD ["flask", "run", "--host=0.0.0.0"]
