# Use an official Python runtime as the base image
FROM python:3.11

# Set the working directory in the container
WORKDIR /app

# Install any needed system dependencies
RUN apt-get update && apt-get install -y wget && apt-get clean

# Copy the requirements file into the container at /app
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install -r requirements.txt

# Clean up any temporary files
RUN rm -rf /var/lib/apt/lists/*

# Set a default command to run when the container starts
CMD ["bash"]
