# Use an official Python runtime as the base image
FROM nvidia/cuda:12.3.1-base-ubuntu20.04

# Set the working directory in the container
WORKDIR /app

# Install any needed system dependencies
RUN apt-get update && apt-get install -y python3 python3-pip

# Copy the requirements file into the container at /app
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install -r requirements.txt

# Clean up any temporary files
RUN rm -rf /var/lib/apt/lists/*

# Set a default command to run when the container starts
CMD ["bash"]